nav:
  - index.md
  - "1. Koneoppiminen": "1_koneoppiminen"
  - "2. Naive Bayes": "2_naivebayes"
  - "3. Puut ja Metsät": "3_puut"
  - "4. k-NN": "4_knn"
  - "5. Klusterointi": "5_klusterointi"
  - exercises.md

